# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shichimi/Documents/PBXProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shichimi/Documents/PBXProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shichimi/Documents/PBXProject/CMakeFiles /Users/shichimi/Documents/PBXProject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shichimi/Documents/PBXProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PBXProject

# Build rule for target.
PBXProject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PBXProject
.PHONY : PBXProject

# fast build rule for target.
PBXProject/fast:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/build
.PHONY : PBXProject/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/option.o: src/option.cpp.o

.PHONY : src/option.o

# target to build an object file
src/option.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/option.cpp.o
.PHONY : src/option.cpp.o

src/option.i: src/option.cpp.i

.PHONY : src/option.i

# target to preprocess a source file
src/option.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/option.cpp.i
.PHONY : src/option.cpp.i

src/option.s: src/option.cpp.s

.PHONY : src/option.s

# target to generate assembly for a file
src/option.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/option.cpp.s
.PHONY : src/option.cpp.s

src/xcodeproj/pbxproj/pbxObject/Util.o: src/xcodeproj/pbxproj/pbxObject/Util.cpp.o

.PHONY : src/xcodeproj/pbxproj/pbxObject/Util.o

# target to build an object file
src/xcodeproj/pbxproj/pbxObject/Util.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/Util.cpp.o
.PHONY : src/xcodeproj/pbxproj/pbxObject/Util.cpp.o

src/xcodeproj/pbxproj/pbxObject/Util.i: src/xcodeproj/pbxproj/pbxObject/Util.cpp.i

.PHONY : src/xcodeproj/pbxproj/pbxObject/Util.i

# target to preprocess a source file
src/xcodeproj/pbxproj/pbxObject/Util.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/Util.cpp.i
.PHONY : src/xcodeproj/pbxproj/pbxObject/Util.cpp.i

src/xcodeproj/pbxproj/pbxObject/Util.s: src/xcodeproj/pbxproj/pbxObject/Util.cpp.s

.PHONY : src/xcodeproj/pbxproj/pbxObject/Util.s

# target to generate assembly for a file
src/xcodeproj/pbxproj/pbxObject/Util.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/Util.cpp.s
.PHONY : src/xcodeproj/pbxproj/pbxObject/Util.cpp.s

src/xcodeproj/pbxproj/pbxObject/pbxCreate.o: src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.o

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxCreate.o

# target to build an object file
src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.o
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.o

src/xcodeproj/pbxproj/pbxObject/pbxCreate.i: src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.i

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxCreate.i

# target to preprocess a source file
src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.i
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.i

src/xcodeproj/pbxproj/pbxObject/pbxCreate.s: src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.s

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxCreate.s

# target to generate assembly for a file
src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.s
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxCreate.cpp.s

src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.o: src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.o

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.o

# target to build an object file
src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.o
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.o

src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.i: src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.i

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.i

# target to preprocess a source file
src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.i
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.i

src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.s: src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.s

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.s

# target to generate assembly for a file
src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.s
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.cpp.s

src/xcodeproj/pbxproj/pbxObject/pbxParser.o: src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.o

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxParser.o

# target to build an object file
src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.o
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.o

src/xcodeproj/pbxproj/pbxObject/pbxParser.i: src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.i

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxParser.i

# target to preprocess a source file
src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.i
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.i

src/xcodeproj/pbxproj/pbxObject/pbxParser.s: src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.s

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxParser.s

# target to generate assembly for a file
src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.s
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxParser.cpp.s

src/xcodeproj/pbxproj/pbxObject/pbxProject.o: src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.o

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxProject.o

# target to build an object file
src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.o
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.o

src/xcodeproj/pbxproj/pbxObject/pbxProject.i: src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.i

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxProject.i

# target to preprocess a source file
src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.i
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.i

src/xcodeproj/pbxproj/pbxObject/pbxProject.s: src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.s

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxProject.s

# target to generate assembly for a file
src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.s
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxProject.cpp.s

src/xcodeproj/pbxproj/pbxObject/pbxUUID.o: src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.o

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxUUID.o

# target to build an object file
src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.o
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.o

src/xcodeproj/pbxproj/pbxObject/pbxUUID.i: src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.i

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxUUID.i

# target to preprocess a source file
src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.i
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.i

src/xcodeproj/pbxproj/pbxObject/pbxUUID.s: src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.s

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxUUID.s

# target to generate assembly for a file
src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.s
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxUUID.cpp.s

src/xcodeproj/pbxproj/pbxObject/pbxWriter.o: src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.o

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxWriter.o

# target to build an object file
src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.o:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.o
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.o

src/xcodeproj/pbxproj/pbxObject/pbxWriter.i: src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.i

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxWriter.i

# target to preprocess a source file
src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.i:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.i
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.i

src/xcodeproj/pbxproj/pbxObject/pbxWriter.s: src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.s

.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxWriter.s

# target to generate assembly for a file
src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.s:
	$(MAKE) -f CMakeFiles/PBXProject.dir/build.make CMakeFiles/PBXProject.dir/src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.s
.PHONY : src/xcodeproj/pbxproj/pbxObject/pbxWriter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PBXProject"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/option.o"
	@echo "... src/option.i"
	@echo "... src/option.s"
	@echo "... src/xcodeproj/pbxproj/pbxObject/Util.o"
	@echo "... src/xcodeproj/pbxproj/pbxObject/Util.i"
	@echo "... src/xcodeproj/pbxproj/pbxObject/Util.s"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxCreate.o"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxCreate.i"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxCreate.s"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.o"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.i"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxObjectSection.s"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxParser.o"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxParser.i"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxParser.s"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxProject.o"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxProject.i"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxProject.s"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxUUID.o"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxUUID.i"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxUUID.s"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxWriter.o"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxWriter.i"
	@echo "... src/xcodeproj/pbxproj/pbxObject/pbxWriter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

